Supprt direct polymer escrow
catalystdao/generalised-relayer pull request #6
Opened 2024-04-23 10:55 UTC by reednaa

2024-04-27 10:03 UTC, jsanmigimeno requested changes

2024-04-27 10:03 UTC, jsanmigimeno commented on src/collector/polymer/polymer.worker.ts
> +        this.filterTopics = [
I don't think this is correct. My understanding is that this means to get the events whose topic 0 is *either* 'SendPacket' or 'this.incentivesAddress'. To get the events whose topic 0 is 'SendPacket *and* topic 1 is 'this.incentivesAddress' it should be [[...SendPacket..., ...this.incentivesAddress...]]

2024-04-27 10:03 UTC, jsanmigimeno commented on src/collector/polymer/polymer.worker.ts
> +        // We need to convert the source chain id to the destination chain using the
```suggestion
        // We need to convert the source channel id to the destination chain using the
```

2024-04-27 10:03 UTC, jsanmigimeno commented on src/collector/polymer/polymer.worker.ts
> +        this.config.polymerChannels[event.sourceChannelId];
Remove this line
```suggestion
```

2024-04-27 10:03 UTC, jsanmigimeno commented on src/collector/polymer/polymer.worker.ts
> +        const destinationChain: string = this.config.polymerChannels[event.sourceChannelId] ?? event.sourceChannelId;
If the mapping of `sourceChannelId` within `polymerChannels` is not found I'd simply return early and not continue to process the event. Having an 'unknown' channel id as the `destinationChain` might cause problems further along the line.

2024-04-29 09:49 UTC, reednaa commented on src/collector/polymer/polymer.worker.ts
> +        this.filterTopics = [
You are correct. I think I was filtering on topic 0 is SendPacket or this.incentivesAddress and not caring what topic 1 was.

2024-04-29 10:39 UTC, jsanmigimeno approved these changes
👍

2024-05-15 11:41 UTC, merged